#! /usr/bin/env php
<?php
declare(strict_types=1);

use SuperKernel\Attribute\Provider\AttributeCollectorProvider;
use SuperKernel\Contract\ApplicationInterface;
use SuperKernel\Di\Container;

require __DIR__ . '/../vendor/autoload.php';

$container = new Container(new AttributeCollectorProvider()());

$application = $container->get(ApplicationInterface::class);

var_dump(get_class($application));

$application->run();