#! /usr/bin/env php
<?php
declare(strict_types=1);

use SuperKernel\Contract\ApplicationInterface;
use SuperKernelTest\Di\ApplicationContext;

require __DIR__ . '/../vendor/autoload.php';

$application = ApplicationContext::getContainer()->get(ApplicationInterface::class);

$application->run();