#! /usr/bin/env php
<?php
declare(strict_types=1);

use SuperKernel\Contract\ApplicationInterface;
use SuperKernel\Di\Provider\ContainerProvider;

require __DIR__ . '/../vendor/autoload.php';

$container = new ContainerProvider()();

$application = $container->get(ApplicationInterface::class);

$application->run();