<?php
declare(strict_types=1);

namespace SuperKernelTest\Di;

use Psr\EventDispatcher\EventDispatcherInterface;
use SuperKernel\Annotation\Autowired;
use SuperKernel\Contract\ApplicationInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class Application extends \Symfony\Component\Console\Application implements ApplicationInterface
{
	#[Autowired]
	protected EventDispatcherInterface $dispatcher;

	public function run(?InputInterface $input = null, ?OutputInterface $output = null): int
	{
		var_dump(get_class($this->dispatcher));

		return parent::run($input, $output); // TODO: Change the autogenerated stub
	}
}